<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 10th Janurary 2013.
 */

if ($this->collection)
{
    /* A whole bunch of sessions from a collection. */
    $sessions = $this->collection->sessions;
}
else if ($this->session)
{
    /* One session to display. */
    $sessions = array();
    array_push($sessions, $this->session);
}
else
{
    /* No session files to display. */
    $sessions = array();
}
?>

<ul class='files-list'>
<?php foreach ($sessions as $session):
         foreach ($session->files as $file): ?>
   <li class='file-<?php if ($file->isDownloadable()): ?>is-downloadable'>
       <span class='ui-icon ui-icon-arrowthickstop-1-s'></span>
       <a href="/datafile/download/file/<?=$file->id?>" target="_blank"><?=$file->name?></a>
   <?php else: ?>not-downloadable'>
       <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$file->name?></span>
   <?php endif; ?>

   <?php if (!$this->historical): ?>
       <a id="file-delete-<?=$file->id?>" class='file-delete'><span class='ui-icon ui-icon-trash'></span></a>
   <?php endif;?>
   </li>
<?php     endforeach;
     endforeach; ?>
</ul>
