<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 10th Janurary 2013.
 */ 

$this->headLink()->appendStylesheet($this->baseUrl('/css/projects.css'));
$this->headScript()->appendFile($this->baseUrl('/js/projects.js'));
?>

<?php if (!$this->project->auto_publish_collections): ?>
<div id="add-collection-button" class="common-button">
    <img src='/images/project-add.png' alt='add' /><br />Create Collection
</div>
<?php endif; ?>

<script type="text/javascript">
$(document).ready(function() {
    $("#add-collection-button").click(addCollection);
});
</script>

<?php if (count($this->project->collections)): ?>
<div id='collection-list-container' class='common-box'>
    <div id='collection-list-title' class='common-title'>
        <span class='ui-icon ui-icon-folder-open'></span>
        Collections for Project: <?=$this->project->activity?>
    </div>
    <div id='collection-list'>
        <ul><?php foreach($this->project->collections as $collection): ?>
            <li class='collection-item'>
                <div class='collection-item-title'>
                    <span class='ui-icon ui-icon-circle-arrow-e'></span>
                    <span>    
                    <?php if ($collection->publish_time): ?>
                        Published on <?=$collection->publish_time->format('d-M-Y') . ' at ' . $collection->publish_time->format('H:i:s');?>.
                    <?php else: ?>
                        Not yet published
                    <?php endif; ?>
                    </span>
                </div>
                <div class='collection-contents'>
                    <div class='collection-details-title'>Details</div>
                    <div class='collection-details'>
                       <div>Started: <?=$collection->getStartTime()->format('d-M-Y H:i:s')?></div>
                       <div>Finished: <?=$collection->getEndTime()->format('d-M-Y H:i:s')?></div>
                       <div>Apparatus(es): </div>
                        
                    </div>
                    <div class='collection-data-title'>Data Files</div>
                    <div class='collection-data'>
                    
                    </div>
                </div>
           </li>
        <?php endforeach; ?></ul>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $("#collection-list .collection-item-title").click(function() {
        var $contents = $(this).siblings(".collection-contents");
        if ($contents.css("display") == "none")
        {
            /* Opening closed contents. */
            $("#collection-list .collection-contents").slideUp();
            $("#collection-list .project-contents-open")
                .removeClass("project-contents-open")
                .children(".ui-icon")
                    .removeClass("ui-icon-circle-arrow-s")
                    .addClass("ui-icon-circle-arrow-e");

            $(this)
                .addClass("project1-contents-open")
                .children(".ui-icon")
                    .removeClass("ui-icon-circle-arrow-e")
                    .addClass("ui-icon-circle-arrow-s");
            $contents.slideDown();
        }
        else
        {
            /* Closing open contents. */
            $contents.slideUp();
            
            $(this).removeClass(".project-contents-open")
                   .children(".ui-icon")
                       .removeClass("ui-icon-circle-arrow-s")
                       .addClass("ui-icon-circle-arrow-e");
        }
    });
});
</script>

<?php else: ?>
<div id='no-collections' class='ui-state-error'>
    <span class='ui-icon ui-icon-alert'></span>
    This project has no collections.
</div>

<?php endif; ?>
