<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 10th Janurary 2013.
 */ 

$this->headLink()->appendStylesheet($this->baseUrl('/css/projects.css'));
$this->headScript()->appendFile($this->baseUrl('/js/projects.js'));
?>

<?php if (!$this->project->auto_publish_collections): ?>
<div id="add-collection-button" class="common-button">
    <img src='/images/project-add.png' alt='add' /><br />Add Collection
</div>
<?php endif; ?>

<script type="text/javascript">
$(document).ready(function() {
    $("#add-collection-button").click(addCollection);
});
</script>

<?php if (count($this->project->collections)): ?>
<div id='collection-list-container' class='common-box'>
    <div id='collection-list-title' class='common-title'>
        <span class='ui-icon ui-icon-folder-collapsed'></span>
        Collections for Project: <?=$this->project->activity?>
    </div>
    <div id='collection-list'>
        <ul><?php foreach($this->project->collections as $collection): ?>
            <li>
                <?=$collection->id?>
           </li>
        <?php endforeach; ?></ul>
    </div>
</div>

<?php else: ?>
<div id='no-collections' class='ui-state-error'>
    <span class='ui-icon ui-icon-alert'></span>
    This project has no collections.
</div>

<?php endif; ?>
