<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 31st October 2012
 */

$this->headLink()->appendStylesheet($this->baseUrl('/css/projects.css'));
$this->headScript()->appendFile($this->baseUrl('/js/projects.js'));
?>

<script type='text/javascript'>
var definitions = [
<?php foreach($this->definitions as $def): ?>
      {
          id:          '<?=strtolower(implode('_', explode(' ', $def->name)))?>',
          name:        '<?=$def->name?>',	
          description: '<?=$def->description?>',	
          hint:        '<?=$def->hint?>',	
          optional:     <?=$def->is_optional ? 'true' : 'false' ?>,	
          regex:       '<?=str_replace('\\', '\\\\', $def->regex)?>',	
      },
<?php endforeach; ?>
];

var userClasses = [
<?php foreach($this->user->userClasses as $uc): ?> 
      {
          id: <?=$uc->id?>,
          name: '<?=$uc->name?>',
      },
<?php endforeach; ?>
];

$(document).ready(function() {
	/* Event handlers. */
	$("#add-project-button").click(displayAddProjectDialog);
});
</script>

<div id="add-project-button" class="common-button">
    <img src='/images/project-add.png' alt='add' /><br />Add Project
</div>

<!-- Project list. -->
<?php if (count($this->user->projects) > 0): ?>
<div id='project-list-container' class='common-box'>
    <div id='project-list-title' class='common-title sahara-form'>
        <span class='ui-icon ui-icon-folder-collapsed'></span>
        Projects
        <div id='project-list-filter-container'>
            <label for='project-list-filter'>Filter:</label>
            <input id='project-list-filter' name='project-list-filter' type='text' />
        </div>
    </div>
    <div id='project-list'>
        <ul>
        <?php foreach ($this->user->projects as $project): ?>
            <li class='project-item'>
                <div class='project-item-title'>
                    <span class='ui-icon ui-icon-circle-arrow-e'></span>
                    <span class='project-activity-id'><?=$project->activity?></span>
                </div>
                <div class='project-buttons'>
                    <div class='project-button-remove'><span class='ui-icon ui-icon-minus'></span> Remove</div>
                <?php if ($project->publish_time && !$project->auto_publish_collections): ?>
                    <div class='project-button-create-collection'><span class='ui-icon ui-icon-plus'></span> Create Collection</div>
                <?php endif; ?>
                <?php if (!$project->publish_time): ?>
                    <div class='project-button-publish'><span class='ui-icon ui-icon-arrowthick-1-e'></span>Publish</div>
                <?php endif; ?>
                </div>
                <div class='project-item-contents'>
                    Details about <?=$project->activity?>.
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$("#project-list .project-button-publish").click(publishProject);
	$("#project-list .project-button-create-collection").click(createCollectionsForProject);
	$("#project-list .project-button-remove").click(removeProject);

	$("#project-list .project-item-title").click(function() {
	    var $contents = $(this).siblings(".project-item-contents");
	    if ($contents.css("display") == "none")
	    {
		    /* Closed so needs to be opened. */
		    $("#project-list .project-item-contents").slideUp();
		    $("#project-list .project-contents-open")
		            .removeClass("project-contents-open")
		            .children(".ui-icon")
		                .removeClass("ui-icon-circle-arrow-s")
		                .addClass("ui-icon-circle-arrow-e");
		   
		    $(this).addClass("project-contents-open")
		            .children(".ui-icon")
		                .removeClass("ui-icon-circle-arrow-e")
		                .addClass("ui-icon-circle-arrow-s");
		    $contents.slideDown();
	    }
	    else
	    {
		    /* Opened so will be closed. */
		    $contents.slideUp();
		    $("#project-list .project-contents-open")
		            .removeClass("project-contents-open")
		            .children(".ui-icon")
		                .removeClass("ui-icon-circle-arrow-s")
		                .addClass("ui-icon-circle-arrow-e");
	    }
	});
});
</script>


<?php endif; ?>
<div id='no-projects' class='ui-state-error' style='display:<?=count($this->user->projects) > 0 ? 'none' : 'block'?>'>
    <span class='ui-icon ui-icon-alert'></span>
    You have no projects.
</div>

