<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 31st October 2012
 */

$this->headLink()->appendStylesheet($this->baseUrl('/css/projects.css'));
$this->headScript()->appendFile($this->baseUrl('/js/projects.js'));

?>

<script type='text/javascript'>
var definitions = [
<?php foreach($this->definitions as $def): ?>
    {
        id:          '<?=strtolower(implode('_', explode(' ', $def->name)))?>',
        name:        '<?=$def->name?>',	
        description: '<?=$def->description?>',	
        hint:        '<?=$def->hint?>',	
        optional:    <?=ord($def->is_optional) === 1 ? 'true' : 'false' ?>,	
        regex:       '<?=$def->regex?>',	
    },
<?php endforeach; ?>
];

var userClasses = [
<?php foreach($this->user->userClasses as $uc): ?> 
{
	id: <?=$uc->id?>,
    name: '<?=$uc->name?>',
},
<?php endforeach; ?>
];

$(document).ready(function() {
	/* Event handlers. */
	$("#add-project-button").click(displayAddProjectDialog);
});
</script>

<div id="add-project-button" class="common-button">
    <img src='/images/project-add.png' alt='add' /><br />Add Project
</div>




