<?php
$cams = new Sahara_Session_Element_Cameras($this->rigClient);
echo $cams;

$rdpApplet = new Sahara_Session_Element_RdpApplet($this->rigClient, array(
	'cl1' => 'SP',
	'cl2' => 'LO'
));
echo $rdpApplet;

$files = new Sahara_Session_Element_HomeFile($this->rigClient);
echo $files;

?>

<div style='position:absolute;top:340px;left:687px;width:275px;padding:5px;' class='ui-state-highlight ui-corner-all'>
	<span class='ui-icon ui-icon-info' style='float:left;margin-right:10px'> </span>
	This is a new and redesigned rig. Please report any errors or quirks you encounter by clicking 'Contact Support'.
</div>

<div style="height:50px">
</div>

