<?php
$this->headLink()->appendStylesheet($this->baseUrl('css/elements/riginfo.css'));
$this->headScript()->appendFile($this->baseUrl('js/home.js'));


$cams = new Sahara_Session_Element_Cameras($this->rigClient);
echo $cams;

$rdpApplet = new Sahara_Session_Element_RdpApplet($this->rigClient, array(
	'cl1' => 'SP',
	'cl2' => 'LO'
));
echo $rdpApplet;

$files = new Sahara_Session_Element_HomeFile($this->rigClient);
echo $files;
?>

<div style="height:20px"></div>

<img class="rigimage" src="/uts/images/Shaker2.jpg" />

<div id="riginfocontainer" class="ui-corner-all overlayelementhide" style="margin-bottom:50px">
	<div class="sessionpanelheader">
		<p><span class="ui-icon ui-icon-lightbulb sessionpanelheadericon"></span>
		System Parameters:</p>
		<a href="#" id="rigcontenthide" class="sessionpanelhide plaina">
			<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Hide
		</a>
	</div>
	<div id="rigcontent" style="display:block">
    	<div id="systemparameter">
			<h3>Mass:</h3>
			<ul>
    			<li>M<sub>1</sub>:  1.1775 kg</li>
    			<li>M<sub>2</sub>:  1.1775 kg</li>
   	 		</ul><br>

			<h3>Stiffness Co-efficient:</h3>
			<ul>
    			<li>k<sub>1</sub>:  370.4 N/m</li>
    			<li>k<sub>2</sub>:  370.4 N/m</li>
   	 		</ul><br>

			<h3>Damping Factor:</h3>
			<ul>
    			<li>c:  0.5 N.m/s</li>
			</ul>
    	</div>
		
	    <div id="systemparameter2">
			<h3>Dimensions:</h3>
			<ul>
				<li></li>
				<li>Masses:  25mm x 200mm x 30mm </li>
				<li>Metal strip:  25mm x 330mm</li>
			</ul><br>

			<h3>Base Excitation:</h3>
			<ul>
				<li></li>
				<li>The motor stroke is 0.7mm (peak to peak amplitude)</li>
			</ul><br><br><br><br>
		</div>
	</div>
</div>


<script type="text/javascript">
//<![CDATA[

$(document).ready( function() {
	$("#rigcontenthide").click(function() {
		if ($("#rigcontent").css('display') == 'block')
		{
			$("#rigcontent").slideUp('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#rigcontenthide").html('<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Show');
		}
		else
		{
			$("#rigcontent").slideDown('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#rigcontenthide").html('<span class="ui-icon ui-icon-arrowthickstop-1-n"></span>Hide');
		}
		resizeFooter();
	});
});

//]]>
</script>