<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Tania Machet (tmachet)
 * @date 03 September 2010
 */

$this->headScript()->appendFile($this->baseUrl('uts/structuralvisualisation/structuralvisualisation.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/structuralvisualisation/structuralvisualisation.css'));

$cam = new Sahara_Session_Element_Cameras($this->rigClient);
$cam->setDraggable(false);


/* Forces buttons. */
$vertforce = new Sahara_Session_Element_MultiButtons($this->rigClient, 'vforce',
    array(
        array(
        	'title'      => "tania",
        	'icon'       => '/uts/fpga/images/switchup.png',
            'click'      => "performPrimitiveJSON('StructuralVisualisationController', 'getConfig', null, checkState, 'Does this work...', false)"
            ),
    ),
    array(
        'orientation' => Sahara_Session_Element_MultiButtons::VERTICAL,
        'top'         => 50,
        'left'        => 550,
        'width'       => 65,
        'height'      => 60
    )
);
    
$horizforce = new Sahara_Session_Element_MultiButtons($this->rigClient, 'hforce',
    array(
    	array(
        	'title'      => 'Horizontal 1',
        	'icon'       => '/uts/fpga/images/switchup.png',
            'click'		 => 'setIO(1)'
                ),
    ),
    array(
        'orientation' => Sahara_Session_Element_MultiButtons::VERTICAL,
        'top'         => 200,
        'left'        => 550,
        'width'       => 65,
        'height'      => 60
    )
);

?>

<div id="SVradio" class="ui-corner-all">
	<h2>Select a model:</h2>
	<ul>
	</ul>
</div>

<div id="modeldesc" class="ui-corner-all overlayelementhide">
	<div class="sessionpanelheader">
		<p style="text-align:left; font-weight:bold"><span class="ui-icon ui-icon-lightbulb sessionpanelheadericon"></span>
		Description of Model:</p>
		<a href="#" id="modelhide" class="sessionpanelhide plaina">
			<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Hide Description
		</a>
	</div>
	<div id="modelcontent" style="display:block">
	</div>
</div>

<div id="forcedesc" class="ui-corner-all overlayelementhide">
	<div class="sessionpanelheader">
		<p style="text-align:left; font-weight:bold"><span class="ui-icon ui-icon-lightbulb sessionpanelheadericon"></span>
		Force application scenario:</p>
		<a href="#" id="forcehide" class="sessionpanelhide plaina">
			<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Hide Description
		</a>
	</div>
	<div id="forcecontent" style="display:block">
		<div id="vforcecontent" style="display:block">  No vertical force is applied (0 Newtons)
		</div>
		<br></br>
		<div id="hforcecontent" style="display:block"> No horizontal force is applied (0 Newtons)
		</div>
	</div>
</div>

<?php
echo $cam;
echo $horizforce;
echo $vertforce;
?>


<script type="text/javascript">
//<![CDATA[

$(document).ready( function() {
	
	performPrimitiveJSON('StructuralVisualisationController','getConfig',null,initConfig,null,null);


     $("#modelhide").click(function() {
		if ($("#modelcontent").css('display') == 'block')
		{
			$("#modelcontent").slideUp('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#modelhide").html('<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Show Description');
		}
		else
		{
			$("#modelcontent").slideDown('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#modelhide").html('<span class="ui-icon ui-icon-arrowthickstop-1-n"></span>Hide Description');
		}
	});

	$("#forcehide").click(function() {
		if ($("#forcecontent").css('display') == 'block')
		{
			$("#forcecontent").slideUp('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#forcehide").html('<span class="ui-icon ui-icon-arrowthickstop-1-s"></span>Show Description');
		}
		else
		{
			$("#forcecontent").slideDown('slow', function() {
				setTimeout("resizeFooter()", 100);
			});
			$("#forcehide").html('<span class="ui-icon ui-icon-arrowthickstop-1-n"></span>Hide Description');
		}
	});

});

//]]>
</script>