<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 20th March 2010
 */

switch ($this->userRole)
{
    case Sahara_Acl::USER:
        $actionMenu = array(
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                        'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))

        );
        break;
    case Sahara_Controller_Action_Acl::PSEUDO_ROLE_QUEUE:
        $actionMenu = array(
            'cancelrequest' => array('title' => 'Cancel Request', 'script' => '_cancelQueue.phtml',
            		'icon' => $this->baseUrl('images/cancel.png'), 'alt' => 'Cancel',
                    'width' => 400,
                    'buttons' => array(
                        'Yes' => 'cancelResourceRequest()',
                        'No' => '$(this).dialog("close")'
                    )),
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                        'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))
        );
        break;
    case Sahara_Controller_Action_Acl::PSEUDO_ROLE_SESSION:
        $actionMenu = array(
            'finishsession' => array('title' => 'Finish Session', 'script' => '_finishSession.phtml',
            		'icon' => $this->baseUrl('images/cancel.png'), 'alt' => 'Cancel',
                    'width' => 400,
                    'buttons' => array(
                        'Yes' => 'finishSession()',
                        'No' => '$(this).dialog("close")'
                    )),
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                        'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))
        );
        break;
    case Sahara_Controller_Action_Acl::PSEUDO_ROLE_BOOKING:
        $actionMenu = array(
            'cancelbooking' => array('title' => 'Cancel Reservation', 'script' => '_cancelBooking.phtml',
            		'icon' => $this->baseUrl('images/cancel.png'), 'alt' => 'Cancel',
                    'width' => 400,
                    'buttons' => array(
                        'Yes' => 'vp.cancel()',
                        'No' => '$(this).dialog("close")'
                    )),
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                        'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))
        );
        break;
    case Sahara_Acl::ACADEMIC:
        $actionMenu = array(
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                       'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))
            );
        break;
   case Sahara_Acl::ADMIN:
        $actionMenu = array(
            'logout' => array('title' => 'Logout', 'script' => '_logout.phtml',
                    'icon' => $this->baseUrl('images/logout.png'), 'alt' => 'logout',
                    'width' => 400,
                    'buttons' => array(
                    	'Yes' => 'location.href="' . $this->url(array('controller' => 'index', 'action' => 'logout')) . '";',
                        'No'  => '$(this).dialog("close");'
                    )),
            'help' => array('title' => 'Help', 'script' => '_help.phtml',
                    'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                    'width' => 650,
                    'buttons' => array(
                       'Close' => '$(this).dialog("close");'
                    )),
        	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                    'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                    'width' => 600,
                    'buttons' => array(
                        'Send' => '$("#feedback_form").submit();',
                        'Cancel' => '$(this).dialog("close");'
                    ))
            );
        break;
    default:
        if ($this->controller == 'index')
        {
            $actionMenu = array(
            	'help' => array('title' => 'Help', 'script' => '_help.phtml',
                        'icon' => $this->baseUrl('images/help.png'), 'alt' => 'help',
                        'width' => 650,
                        'buttons' => array(
                            'Close' => '$(this).dialog("close");'
                        )),
            	'support' => array('title' => 'Contact Support', 'script' => '_feedback.phtml',
                        'icon' => $this->baseUrl('images/feedback.png'), 'alt' => 'feedback',
                        'width' => 600,
                        'buttons' => array(
                            'Send' => '$("#feedback_form").submit();',
                            'Cancel' => '$(this).dialog("close");'
                        ))
            );
        }
        else $actionMenu = array();
        break;
}

/* The help page is special, as it can be access from any other page. */
if ($this->controller == 'index' && $this->action == 'help') $actionMenu = array();
?>

<?php if (count($actionMenu)):?>
<div id="actionbar">
	<ul id="actionbarlist">
	<?php foreach ($actionMenu as $id => $action): ?>
		<li>
			<a id="<?=$id?>" class="actiondialogbutton plaina ui-corner-all" href="#">
					<img src="<?=$action['icon']?>" alt="<?=$action['alt']?>"
					style="margin-bottom:<?=strlen($action['title']) < 10 ? '10' : '0'?>px" /><br />
			        <?=$action['title']?></a>
			<? echo $this->render('actionbuttons/' . $action['script']); ?>
		</li>
	<?php endforeach; ?>
	</ul>
</div>

<script type="text/javascript">

$(document).ready(function() {
<?php foreach ($actionMenu as $id => $action): ?>
	$('#<?=$id?>dialog').dialog ({
		autoOpen: false,
		width:<?=$action['width']?>,
		modal: true,
		resizable: false,
		buttons: {
		<?php $lastScript = end($action['buttons']);
		    foreach ($action['buttons'] as $name => $funcScript): ?>
			"<?=$name?>": function() { <?=$funcScript?> }<?php if ($lastScript != $funcScript) echo ','?>
		<?php endforeach; ?>
		},
		open: function (event, ui) {
			/* Move all the applet, object and embeds to a margin right off
			 * screen. */
			appletMargins = new Array();
			var applets = $("applet").toArray();
			for (var i in applets)
			{
				appletMargins[i] = applets[i].style.marginLeft;
				applets[i].style.marginLeft = "10000px";
			}

			objectMargins = new Array();
			var objects = $("object").toArray();
			for (var i in objects)
			{
				objectMargins[i] = objects[i].style.marginLeft;
				objects[i].style.marginLeft = "10000px";
			}

			embedMargins = new Array();
			var embeds = $("embed").toArray();
			for (var i in embeds)
			{
				embedMargins[i] = embeds[i].style.marginLeft;
				embeds[i].style.marginLeft = "10000px";
			}

			/* Remove the validation tooltips. */
			$(".formError").remove();
		},
		close: function (event, ui) {
			/* Move the applet, object and embeds back to their original
			 * position. */
				var applets = $("applet").toArray();
				for (var i in applets)
				{
					applets[i].style.marginLeft = appletMargins[i];
				}

				var objects = $("object").toArray();
				for (var i in objects)
				{
					objects[i].style.marginLeft = objectMargins[i];
				}

				var embeds = $("embed").toArray();
				for (var i in embeds)
				{
					embeds[i].style.marginLeft = embedMargins[i];
				}
				/* Remove the validation tooltips. */
				$(".formError").remove();
		}

	});

	$('#<?=$id?>').click(function(){
		$('#<?=$id?>dialog').dialog('open');
		return false;
	});
<?php endforeach; ?>
});
</script>
<?php endif?>


