<div id="footer" class="ui-corner-top" style='height:45px'>
  
  <p id="footer-labshare-logo" style="position:absolute;left:0;top:0">
      <a class="plaina alrpad" href="http://www.labshare.edu.au" target="_new">
        <img style='margin-top:5px;height:50px;width:120px' src="/images/labshare.png" style="border-width:0" />
      </a>
  </p>
  
  <div style='text-align:right;'>
    <p id="footer-iefix" style="text-align:right;width:100%;">
        <p style='text-align:right;'>
            <b>ABN:</b> 15 211 513 464. 
            <b>CRICOS number:</b> 00026A.
            <b>Phone:</b> +61 2 9351 2222.
        </p>
        <p style='text-align:right;'>
          <b>Authorised by:</b> Director, Academic Services, Information Communications Technology.
        </p>
        <p style='text-align:right'>
            <a href="http://sydney.edu.au/contact.shtml">Contact the University</a> |
            <a href="http://sydney.edu.au/disclaimer.shtml">Disclaimer</a> |
            <a href="http://sydney.edu.au/privacy.shtml">Privacy</a> |
            <a href="http://sydney.edu.au/privacy.shtml">Accessibility</a>
        </p>
    </p>
    <p style="clear:both"></p>
  </div>
</div>

<!--[if lte IE 7]>
<style>
#footer-iefix {
    margin-top:-12px
}
</style>
<![endif]-->

<!--[if lte IE 6]>
<style>
#footer-labshare-logo {
    display:none;
}
</style>
<![endif]-->