<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 17th March 2010
 */

$config = Zend_Registry::get('config');

/* Set up header image. */
($headerImg = $config->header->logoGraphic) != null || $headerImg = 'images/logo.png';
$headerImg = $this->baseUrl($headerImg);

$headerImgLink = $config->header->logoLink == null ? 'http://sourceforge.net/projects/labshare-sahara/' :
        $config->header->logoLink;

($headerName = $config->header->nameImage) != null || $headerName = 'images/Sahara.png';
$headerName = $this->baseUrl($headerName);

?>

<!--[if IE 6]>
<script src="<?=$this->baseUrl("js/DD_belatedPNG.js")?>"></script>
<script>
  DD_belatedPNG.fix('img');
</script>
<![endif]-->

<div class="headerimg" >
<?php if ($headerImgLink != null): ?>
   	<a target="_blank" href="<?=$headerImgLink?>">
		<img src="<?=$headerImg?>" alt="Institution Logo" />
    </a>
<?php endif; ?>
</div>

<div class="headerimg" >
	<img src="<?=$headerName?>" alt="Lab Name" />
</div>

<?php if ($config->header->useLabshare): ?>
<div id="labshareimg">
	<a target="_blank" href="http://www.labshare.edu.au/">
		<img src="<?=$this->baseUrl('images/labshare.png')?>" alt="LabShare" />
	</a>
</div>
<?php endif; ?>
