<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 20th March 2010
 */
$this->headLink()->appendStylesheet($this->baseUrl('css/form.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/jqtransform.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/validationEngine.jquery.css'));
$this->headScript()->appendFile($this->baseUrl('js/jquery.jqtransform.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery.validationEngine-en.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery.validationEngine.js'));
$this->headScript()->appendScript('

');
?>

<?php if (count($this->messages)):?>
	<div class="ui-state-error ui-corner-all">
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    	<?php if (count($this->messages) > 1):?>
    		<ul>
    		<?php foreach ($this->messages as $m): ?>
    			<li><?=$m?></li>
    		<?php endforeach; ?>
    		</ul>
    	<?php else: ?>
    		<?=$this->messages[0]?>
    	<?php endif; ?>
		</p>
	</div>
<?php endif; ?>

<form id="formid" method="POST">
	<?=$this->form->getDisplayGroup('auth_form')->render()?>
	<div align="right" class="ui-corner-all">
		<?=$this->form->getElement('login')->render()?>
	</div>
</form>

<script type="text/javascript">
$(function() {
    $("#formid").jqTransform();
    $("#formid").validationEngine();
});
</script>

