<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 28th February 2010
 */
?>

<div class="contentheader">
	<h2>User and System Requirements</h2>
</div>

<div id="helppage">
	<p>The following sections outline the general procedure for accessing this remote laboratory. Most
	importantly, the software that runs the Remote Labs and provides access to the rigs through a web browser is
	called <a class="plaina" href="http://sourceforge.net/projects/labshare-sahara/" target="_blank"
	style="font-weight:bold">SAHARA Labs</a>.</p>

	<h2>Compatibility Matrix</h2>
	<table border="1">
		<tr>
			<th>
				Operating system
			</th>
			<th>
				Browser (tested and supported)
			</th>
			<th>
				Plugins
			</th>
			<th>
				Screen Resolution
			</th>
		</tr>
		<tr>
			<td>
				Windows XP SP2<br />
				Windows Server 2003<br />
				Windows Vista<br />
				Windowx 7<br />
			</td>
			<td>
				<ul>
					<li>Internet Explorer 7</li>
					<li>Internet Explorer 8</li>
					<li>Internet Explorer 9 (preferred)</li>
					<li>Mozilla Firefox 3.6 and above</li>
					<li>Google Chrome (latest)</li>
					<li>Opera 11.50</li>
				</ul>
				<strong>NOTE: </strong> Internet Explorer 6 works in a functionally limited mode. It is strongly
				recommended to upgrade to the latest version of Internet Explorer.
			</td>
			<td>

			</td>
			<td>

			</td>
		</tr>
		<tr>
			<td>
				Mac OS X Snow Leopard<br />
				Mac OS X Lion<br />
			</td>
			<td>

			</td>
			<td>

			</td>
			<td>

			</td>
		</tr>
		<tr>
			<td>
				Linux (any recent distrubution)
			</td>
			<td>

			</td>
			<td>

			</td>
			<td>

			</td>
		</tr>
	</table>

	<h2>Network</h2>
	<p>For the purpose of using the Remote Labs rigs, it is assumed that users have access to a workstation with
	properly working operating system. The current workstation must also have Internet connectivity, preferably
	with a bandwidth of at least 512kbps downstream.</p>

	<h2>Web Browsers</h2>

	<h2>Java Runtime Engine</h2>

	<h2>Video Plugins</h2>

	<h2></h2>
</div>



<script>
$(document).ready(function() {
	$("#actionbar").hide();
});
</script>
