<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 9th March 2010
 */

$this->headLink()->appendStylesheet($this->baseUrl('/css/bookings.css'));
$this->headScript()->appendFile($this->baseUrl('/js/bookings.js'));


$header = $this->permission->displayName;
if (!$header) $header = $this->permission->resource->resourceName;

list($year, $mon, $day) = explode('-', $this->currentDay, 3);
$sDate = "$day/$mon/$year";
list($year, $mon, $day) = explode('-', $this->endDay, 3);
$eDate = "$day/$mon/$year";
?>

<div class="contentheader">
	<h2>Reservation for <?=$this->stringTransform($header, '_', ' ')?></h2>
</div>

<?php if ($this->canBook): ?>

<!-- Day picker bar. -->
<div id="daypickerbar">
	<div id="leftarrowbox" class="arrowbox">
		<a id="leftarrow" class="plaina disdaybutton ui-corner-all">
			<img src="<?=$this->baseUrl('/images/dis_leftarrow.png')?>" alt="Previous" />
		</a>
		<div id="daybuttonlabelleft" class="daybuttonlabel">Previous Day</div>
	</div>
	<div id="daypickercontainer">
		<div id="daypickerinner">
			<div id="daypickerleft">&nbsp;</div>
    		<div id="daypickerinput" class="jqTransformInputWrapper">
    			<div class="jqTransformInputInner">
    				<div>
    					<input id="daypicker" class="jqTransformInput jqtranformdone" type="text" value="<?=$sDate?>"/>
					</div>
    			</div>
    		</div>

    		<div id="daypickericonbox" class="arrowbox">
    			<a id="daypickericon" class="plaina daybutton ui-corner-all">
    				<img src="<?=$this->baseUrl('/images/daypicker.png')?>" alt="Pick" />
    			</a>
    		</div>
		</div>
	</div>

	<div id="rightarrowbox" class="arrowbox">
		<a id="rightarrow" class="plaina daybutton ui-corner-all">
			<img src="<?=$this->baseUrl('/images/rightarrow.png')?>" alt="Next" />
		</a>
		<div id="daybuttonlabelright" class="daybuttonlabel">Next Day</div>
	</div>
</div>

<script type="text/javascript">
//<!--
var vp = new BookingPage('<?=$sDate?>', '<?=$eDate?>');

$(document).ready(function() {
	$('#daypicker').datepicker({
		defaultDate: vp.getCurrent(),
		minDate: vp.getStart(),
		maxDate: vp.getEnd(),
		dateFormat: 'dd/mm/yy',
		onSelect: function(dateText, inst) {
			vp.changeDate(dateText);
		}
	});

	$("#daypickerinput").hover(
		function() {
			$(this).addClass("jqTransformInputWrapper_hover");
		},
		function() {
			$(this).removeClass("jqTransformInputWrapper_hover");
		}
	 );

	 $("#daypickericon").click(function() { $("#daypicker").datepicker("show"); });
	 $("#leftarrow").click(function() { vp.previousDay(); });
	 $("#rightarrow").click(function() { vp.nextDay(); } );
});
//-->
</script>

<div style="clear:both"></div>

<div id="bookingstimecontainer" class="ui-corner-all">
	<div id="bookingstimetitle" class="ui-corner-all"><?=$sDate?></div>

</div>


<?php else: ?>
<h2>Maximum bookings elasped.</h2>
<?php endif; ?>
