<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 21st February 2010
 */

$this->headLink()->appendStylesheet($this->baseUrl('css/queue.css'));
$this->headScript()->appendScript('
$(document).ready(function() {
	$("#userclasstabs").tabs();

	if (/msie|MSIE 6/.test(navigator.userAgent) || /msie|MSIE 7/.test(navigator.userAgent))
	{
		$(".permissionbar h3").css("margin", "5");
		$(".permissionbutton").css("margin-top", "0");
		$(".permissionbutton").css("margin-bottom", "0");
	}
});
');

/* Sort the user classes by name. */
$keys = array_keys($this->userPermissions);
sort($keys, SORT_STRING);

/* Generate the tab div ids. */
$tabHref = array();
$i = 1;
foreach ($keys as $key)
{
    $tabHref[$key] = 'userClass' . $i++;
}

/* Work out the height of the tab div. */
$tabHeight = 0;
foreach ($this->userPermissions as $permissions)
{
    $height = 0;
    foreach ($permissions as $type => $perms)
    {
        $height += ceil(count($perms) / 4) * 100 + ceil((count($perms) / 4)) * 50;
    }
    if ($height > $tabHeight) $tabHeight = $height;
}
?>

<div class="contentheader">
	<h2>Permission List</h2>
</div>

<?php if (!$this->noPermissions): ?>
	<div id="userclasstabs">
		<ul>
	    <?php foreach ($keys as $class): ?>
			<li>
				<a href="#<?=$tabHref[$class]?>"><?=$this->stringTransform($class, '_', ' ')?></a>
			</li>
	    <?php endforeach; ?>
	    </ul>
	<?php foreach ($tabHref as $class => $id):?>
		<div id="<?=$id?>" style="height:<?=$tabHeight?>px">
		<!-- Permission list for class <?=$class?> -->
		<?php foreach ($this->userPermissions[$class] as $type => $typePerm):
		          if (count($typePerm)): ?>
			<div class="permissionbar">
				<h3><?=$type?></h3>
				<ul class="permissionlistbar">
					<?php foreach ($typePerm as $perm): ?>
					<li>
						<a id="<?=$perm['id']?>" class="permissionbutton plaina ui-corner-all" href="#">
						<?php if (!$perm['active']): ?>
							<img class="permissionicon" src="<?=$this->baseUrl('images/permission_expired.png')?>" alt="Expired" />
						<?php elseif ($perm['locked']):?>
							<img class="permissionicon" src="<?=$this->baseUrl('images/permission_locked.png')?>" alt="Locked" />
						<?php else: ?>
							<img class="permissionicon" src="<?=$this->baseUrl('images/permission_launch.png')?>" alt="Allowed" />
						<?php endif;?>
						    <?=$this->stringTransform($perm['resource'], '_', ' ')?>
						</a>
					</li>
					<?php endforeach;?>
				</ul>
			</div>
		<?php    endif;
		     endforeach; ?>
		</div>
	<?php endforeach; ?>
	</div>

	<!-- Legend for icon meaning. -->
	<div id="iconlegend">
		<h3>Legend:</h3>
		<p><img src="<?=$this->baseUrl('images/permission_launch.png')?>" alt="Allowed" />
		Active: You may queue for the resource.</p>
		<p><img src="<?=$this->baseUrl('images/permission_expired.png')?>" alt="Allowed" />
		Not active: The permission is not active at the current time.</p>
		<p><img src="<?=$this->baseUrl('images/permission_locked.png')?>" alt="Allowed" />
		Locked: The resource is active but locked. You must supply a pass key before you can queue.</p>
	</div>
<?php else: ?>
	<div class="ui-state-error ui-corner-all alertdiv centercontent" style="width:350px">
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    		Sorry, you do not have permission to use any rigs.
    	</p>
    </div>
<?php endif; ?>
