<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 29th March 2010
 */

$this->headLink()->appendStylesheet($this->baseUrl('css/queue.css'));
$this->headScript()->appendFile($this->baseUrl('js/queue.js'));

$c = Zend_Registry::get('config')->queue->interval;
$this->headScript()->appendScript('

$(document).ready(function() {
	tInterval = setInterval("updateQueueInfo()", '. ($c ? $c * 1000 : 60000) .');
});

');

$lastDig = $this->pos % 10;
if ($lastDig == 1)      $suf = 'st';
else if ($lastDig == 2) $suf = 'nd';
else if ($lastDig == 3) $suf = 'rd';
else                    $suf = 'th';

$mins = floor($this->time / 60);
$secs = $this->time % 60;
?>
<div class="contentheader">
	<h2>Queue</h2>
</div>

<div id="queueinfo">
    <div id="queuepos">
    	Your position is: <span id="queueposnum"><?="$this->pos$suf"?></span><br />
    	<img src="<?=$this->baseUrl('images/queuing.gif')?>" alt="Queuing" />
    </div>
    <div id="queuetime">
    	In queue <span><?=$mins?></span> <?=$mins > 1 ? 'minutes' : 'minute'?>, <span><?=$secs?></span> <?=$secs > 1 ? 'seconds' : 'second'?>.
    </div>
    <div id="queueredirectinfo" class="ui-state-highlight ui-corner-all">
    	<span class="ui-icon ui-icon-info"></span>
    	You will be automatically redirected to the rig when you are assigned to one.
    </div>

</div>