<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 21st March 2010
 */
$this->headLink()->appendStylesheet($this->baseUrl('css/info.css'));
$this->headScript()->appendFile($this->baseUrl('js/galleria/galleria.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery.galleria.pack.js'));
$this->headScript()->appendFile($this->baseUrl('js/galleria/themes/Sahara/galleria.sahara.js'));

?>
<script>
	$("document").ready(function(){
		$('ul.gallery_list').galleria({
			history   : true, // activates the history object for bookmarking, back-button etc.
			clickNext : true, // helper for making the image clickable
			onImage   : function(image,caption,thumb) { // let's add some image effects for demonstration purposes

			// fade in the image & caption
			if(! ($.browser.mozilla && navigator.appVersion.indexOf("Win")!=-1) ) { // FF/Win fades large images terribly slow
				image.css('display','none').fadeIn(1000);
			}
			caption.css('display','none').fadeIn(1000);

			// fetch the thumbnail container
			var _li = thumb.parents('li');

			// fade out inactive thumbnail
			_li.siblings().children('img.selected').fadeTo(500,0.4);

			// fade in active thumbnail
			thumb.fadeTo('fast',1).addClass('selected');

			// add a title for the clickable image
			image.attr('title','Next image >>');
		},
		onThumb : function(thumb) { // thumbnail effects goes here

			// fetch the thumbnail container
			var _li = thumb.parents('li');

			// if thumbnail is active, fade all the way.
			var _fadeTo = _li.is('.active') ? '1' : '0.4';

			// fade in the thumbnail when finnished loading
			thumb.css({display:'none',opacity:_fadeTo}).fadeIn(1500);

			// hover effects
			thumb.hover(
				function() { thumb.fadeTo('fast',1); },
				function() { _li.not('.active').children('img').fadeTo('fast',0.4); } // don't fade out if the parent is active
			)
		}
	});
});
</script>

<div class="gallery" >
<ul class="gallery_list">
    <li><img src="<?=$this->baseUrl('images/alert.png')?>" alt="Morning" title="Is it morning, or end of day?"></li>
    <li><img src="<?=$this->baseUrl('images/cancel.png')?>" alt="Morning not yet" title="Who says it is morning?"></li>
    <li><img src="<?=$this->baseUrl('images/alert.png')?>" alt="Breakfast" title="Breaking fast at last"></li>
    <li class="active"><img src="<?=$this->baseUrl('images/alert.png')?>" alt="Mirrors all around" title="Mirror, mirror on the wall"></li>
    <li><img src="<?=$this->baseUrl('images/alert.png')?>" alt="Road blocked" title="Road blocked by a flock of sheep"></li>
    <li><img src="<?=$this->baseUrl('images/cancel.png')?>" alt="Ostrich egg shells" title="Table lamps created with ostrich egg shells"></li>
    <li><img src="<?=$this->baseUrl('images/cancel.png')?>" alt="The Ocean" title="An endless sheet of water, the Indian Ocean"></li>
</ul>

<p class="nav">
<a href="#" onclick="$.galleria.prev(); return false;">« previous</a> | <a href="#" onclick="$.galleria.next(); return false;">next »</a></p>

</div>

