<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 13th February 2010
 */

$this->headScript()->appendFile('/uts/hydro/hydro.js');
$this->headLink()->appendStylesheet('/uts/hydro/hydro.css');
$this->headLink()->appendStylesheet('/uts/hydro/hydro-ie.css', 'screen', 'lt IE 9')
?>

<div id="hydro">
	<!--  Experiment canvas. -->
</div>

<a id="hydroselectorbutton" class="hydrobutton ui-corner-all">
	<img src="<?=$this->baseUrl('/uts/hydro/images/experiments.png')?>" alt="launch" />
	Change Experiment
</a>

<a id="hydroresetbutton" class="hydrobutton ui-corner-all">
	<img src="<?=$this->baseUrl('/uts/hydro/images/experiments.png')?>" alt="launch" />
	Restore Positions
</a>

<a id="datadownloadbutton" class="hydrobutton ui-corner-all">
	<img src="<?=$this->baseUrl('/uts/hydro/images/datadownload.png')?>" alt="download" />
	Download Data
</a>

<script type="text/javascript">
var hydro = new Hydro();
$(document).ready(function() {
	hydro.init();

	/* Button behaviours. */
  	$("#hydroselectorbutton").click(function() {
  	  	hydro.changeExperiment();
  	});

  	$("#hydroresetbutton").click(function() {
  	  	hydro.resetPosition();
  	});

	$("datadownloadbutton").click(function() {

	});
});
</script>

<!-- Debug panel. -->
<div id="hydrodebugpanel" class="sessionpanel ui-corner-all">
	<div class="sessionpanelheader">
		<p><span class="ui-icon ui-icon-wrench sessionpanelheadericon"></span>Debug</p>
	</div>
	<div id="hydrodebug"></div>
</div>

<div style="clear:both; margin-bottom:40px;"> </div>
