<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 5th March 2011
 */
$this->headLink()->appendStylesheet('/css/partials/permkey.css');
?>

<div id="permkeybutton" class="commonbutton">
	<span class="ui-icon ui-icon-key"></span>
	Activate Permission
</div>

<div id="permkeydialog" title="Permission Activation:">
	<div id="permkeyform">
		<div id="permkeyerror" class="ui-state ui-state-error ui-corner-all">
			<span class="ui-icon ui-icon-alert"> </span>
			<p> </p>
		</div>
    	Enter a permission key to activate it's permission:
    	<div id="permkeyouter">
    		<div id="permkeylabel">Key:</div>
    		<div id="permkeyfield" class="jqTransformInputWrapper">
    			<div class="jqTransformInputInner"><div>
    				<input id="permkey" type="text" name="permkey" id="permkey" class="validate[required] jqTranformInput jqTransformdone" />
    			</div></div>
    		</div>
    	</div>
    	<div id="permkeyclear"></div>
	</div>
	<div id="permkeyloading">
		<img src="/images/ajax-loading.gif" alt="Loading" />
		<br />
		Please wait...
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$("#permkeydialog").dialog({
		autoOpen: false,
		modal: true,
		width: 350,
		resizable: false,
		buttons: {
			Activate: function() {
				if ($("#permkeyform").validationEngine("validateField", "#permkey")) return;

				/* Tear down the dialog. */
				$("#permkeyform").hide();
				$("#permkeyloading").show();
				$(this).dialog({
					closeOnEscape: false
				}).parent().children(".ui-dialog-titlebar, .ui-dialog-buttonpane").hide();

				$.get(
					'/index/permactivate',
					{
						pkey: $("#permkey").val()
					},
					function(response) {
						if (typeof response != "object") window.location.reload();

						/* If it was successful, reload the page to show the new permission. */
						if (response.success)
						{
							$("#permkeydialog").empty().append(
									"<div id='permkeysuccess'>Success, refreshing...</div>"
							);
							window.location.reload();
							return;
						}

						/* Restore applet. */
						$("#permkeyform").show();
						$("#permkeyloading").hide();
						$("#permkeydialog").dialog({
							closeOnEscape: true
						}).parent().children(".ui-dialog-titlebar, .ui-dialog-buttonpane").show();

						$("#permkeyerror").show()
							.children("p").text(response.error);
					}
				);
			},
			Close: function() {
				$(".permkeyformError").remove();
				$("#permkeyerror").hide();
				$(this).dialog("close");
			}
		}
	});

	$("#permkeybutton").click(function() {
		$("#permkeydialog").dialog("open");
	});

	$("#permkeyfield")
		.hover(
			function() { $(this).addClass("jqTransformInputWrapper_hover"); },
			function() { $(this).removeClass("jqTransformInputWrapper_hover"); })
		.focus(function() { $(this).addClass("jqTransformInputWrapper_focus"); })
	 	.focusin(function() { $(this).addClass("jqTransformInputWrapper_focus"); })
	 	.focusout(function() { $(this).removeClass("jqTransformInputWrapper_focus"); });
});
</script>