<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 20th March 2010
 */
$form = new Sahara_Feedback_Form();
?>

<div id="supportdialog" class='actionbardialog' title="Contact Support">
	The request will be sent to the Labs support team:
	<form id="feedback_form" class="saharaform" action="<?=$this->baseUrl('/index/feedback')?>">
	    <?=$form->getDisplayGroup('feedback_form')->render()?>
	</form>
</div>

<script type="text/javascript">

hasConfAdded = false;
$(document).ready(function () {
	var browserInfo =
		"<input type='hidden' name='useragent' value='" + escape(navigator.userAgent) + "'/>" +
		"<input type='hidden' name='javaenabled' value='" + (navigator.javaEnabled() ? "true" : "false") + "' />" +
		"<input type='hidden' name='utcoffset' value='" + (new Date().getTimezoneOffset() * 60) + "' />";
	if (navigator.plugins)
	{
		browserInfo += "<input type='hidden' name='navplugins' value='";
		var i;
		for (i = 0 ; i < navigator.plugins.length; i++)
		{
			browserInfo += escape(navigator.plugins[i].name) + "=" + escape(navigator.plugins[i].filename) + ";";
		}
		browserInfo += "' />";
	}

    $("#feedback_form")
    	.append(browserInfo)
    	.validationEngine({
        	 ajaxFormValidation: true,
        	 onAjaxFormComplete: function(form, status, errors, options) {
    		 	$("#supportdialog").empty().append(
    		 		"<div id='feedback_form_sent'>" +
    		 			"Thank you, we will respond to your support request as soon as possible." +
    		 		"</div>"
    			).dialog("option", "buttons", {
    				'Close': function() {
    					$(this).dialog('close');
    				}
    			});
    		 	$("#feedback_form_sent").fadeIn("slow");
	     	}
	 	});

	$("#feedback_form div.jqTransformInputWrapper, #feedback_form input.jqTransformInput").css("width", "100%");
});

</script>