<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 5th August 2010
 */
?>

<div id="unauthhelpdialog" class="helpdialog" title="Help and Troubleshooting">
	<div class="helpcontents" >
		<div class="helptitle ui-widget-header ui-corner-all">Help:</div>
		<p>A username and password is required to access the Remote Labs. A proper
		username and password are provided by the institution that hosts Remote
		Labs. Please click on the "<span>Contact Support</span>" button to request
		a username and password.</p>

		<div class="helptitle ui-widget-header ui-corner-all">Troubleshooting:</div>
		<div id="helpaccordian">
			<h3><a href="#">System Requirements</a></h3>
			<div>
				Operating System: Windows Server 2003, Windows XP, Windows Vista, Linux,
			   	and Mac OS 10.5 and above.<br />
				Browser (tested and supported): Mozilla Firefox 3.0 and above, Chrome,
					 Internet Explorer 6 and above, Safari<br />
				Screen Resolution: 1024x768<br />
			</div>
			<h3><a href="#">I don't have an account. How do I request/receive a username and password?</a></h3>
			<div>
				 Please click on the "Contact Support" button to request a username and password.
			</div>
			<h3><a href="#">I have an account, but I can't access and have received an error message.</a></h3>
			<div>
				You may need to reactivate your account for the Remote Labs. Please click on the
				"Contact Support" button and provide specific details of the erroe you are receiving.
			</div>
			<h3><a href="#">I forgot my username and/or password.</a></h3>
			<div>
				Please click on the "Contact Support" button to request your username and/or password.
			</div>
		</div>
		<div class="helplink">
			<a href="#">
    			<span class="ui-icon ui-icon-arrow-1-e"></span>
    			More help and troubleshooting.
			</a>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$("#helpaccordian").accordion({
		active: "none",
		collapsible: true
	});

	$("#helpaccordian .ui-accordion-header").css("background", "none");
});
</script>