<?php
$this->headScript()->appendFile($this->baseUrl('uts/coupledtanksnew/coupledtanksnew.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/coupledtanksnew/coupledtanksnew.css'));
?>

<div id="coupled-tanks-anchor">
    <!-- Interface goes here! -->
</div>

<script type="text/javascript">
$(document).ready(function() {
	var inter = new WaterLevelControl("coupled-tanks-anchor");
	inter.setup();
	inter.run();
});
</script>
