<?php
$this->headScript()->appendFile($this->baseUrl('uts/coupledtanksnew/coupledtanksnew.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/coupledtanksnew/coupledtanksnew.css'));
?>

<!-- IE 9 Gradient support -->
<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->

<div id="coupled-tanks-anchor">
    <!-- Interface goes here! -->
</div>

<script type="text/javascript">
$(document).ready(function() {
	var inter = new WaterLevelControl("coupled-tanks-anchor");
	inter.setup();
	inter.run();
});
</script>
