<?php
/**
 * Robot web interface.
 */

$this->headScript()->appendFile($this->baseUrl('webui/webui.js'));
$this->headLink()->appendStylesheet($this->baseUrl('webui/webui.css'));
$this->headLink()->appendStylesheet($this->baseUrl('webui/webui-flat.css'));

$this->headScript()->appendFile($this->baseUrl('uts/robot/robot-imperative.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/robot/robot.css'));

/* Canvas compatability implementation for Internet Explorer 8 and earlier. */
$this->headScript()->appendFile($this->baseUrl('js/excanvas.js'),
        'text/javascript',
        array('conditional' => 'lt IE 9')
);
?>

<div id="robot-anchor">
    <!-- Interface goes here! -->
</div>


<script type="text/javascript">
$(document).ready(function() {
    var dp;
    new WebUIApp({
        anchor: "#robot-anchor",
        windowToggle: true,
        controller: "RobotController",
        dataAction: "data",
        theme: Globals.THEME.flat	,
        cookie: "robot",
        dataPeriod: 100,
        dataDuration: 60,
        pollPeriod: 1000,
        height: 1750,
        widgets: [
			new AMCL("amcl", {
				title: "Map & AMCL",
				action: "setAMCLInitialPose",
				initialPoseField: "amcl-initial-pose",
				poseField: "amcl-pose",
				particlesField: "amcl-particles",
				width: 679,
				height: 395,
				left: 0,
				top: 0,
				resizable: false,
				expandable: false,
			}),
            dp = new DPad("dpad", {
                title: "Movement",
               	action: "setSpeed",
                speedField: "robot-linear",
                yawField: "robot-angular",
                windowed: false,
                top: 150,
                left: -165
            }),
            new Ranger("ranger-panel", {
                title: "Hokuyo",
                width: 330,
                height: 360,
            }),
            new CodeUpload("code-upload", {
				title: "ROS Upload",
				width: 400,
				height: 370,
				expandable: false,
				dpad: dp
            }),
            new InitError(),
        ]
    }).setup().run();
});
</script>

<iframe style="display:none" id="code-upload-target" name="code-upload-frame"></iframe>
