<?php

/* Web user interface. */
$this->headScript()->appendFile($this->baseUrl('webui/webui.js'));
$this->headLink()->appendStylesheet($this->baseUrl('webui/webui.css'));
$this->headLink()->appendStylesheet($this->baseUrl('webui/webui-flat.css'));

/* Shake Table interface implementation. */
$this->headScript()->appendFile($this->baseUrl('uts/shaketable/shaketable_3dof.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/shaketable/shaketable.css'));

/* Canvas compatability implementation for Internet Explorer 8 and earlier. */
$this->headScript()->appendFile($this->baseUrl('js/excanvas.js'),
        'text/javascript',
        array('conditional' => 'lt IE 9')
);

/* Touch events punching to mouse events. */
$this->headScript()->appendFile($this->baseUrl('uts/coupledtanksnew/jquery.ui.touch-punch.js'));
?>

<div id="shake-table-anchor">
    <!-- Interface goes here! -->
</div>


<script type="text/javascript">
$(document).ready(function() {
	ShakeTable(true);
});
</script>