<?php

/**
 * Wind Tunnel web interface.
 */

$this->headScript()->appendFile($this->baseUrl('uts/windtunnel/windtunnel.js'));
$this->headLink()->appendStylesheet($this->baseUrl('uts/windtunnel/windtunnel.css'));

/* Canvas compatability implementation for Internet Explorer 8 and earlier. */
$this->headScript()->appendFile($this->baseUrl('js/excanvas.js'),
        'text/javascript',
        array('conditional' => 'lt IE 9')
);

/* Touch events punching to mouse events. */
$this->headScript()->appendFile($this->baseUrl('uts/coupledtanksnew/jquery.ui.touch-punch.js'));
?>

<div id="wind-tunnel-anchor">
    <!-- Interface goes here! -->
</div>


<script type="text/javascript">
$(document).ready(function() {
	var inter = new WindTunnel("wind-tunnel-anchor");
	inter.setup();
	inter.run();
});
</script>