<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 21st March 2010
 */
$config = Zend_Registry::get('config');
($contactName = $config->contact->name) != null || $contactName= 'Labshare Contact - Labshare Guru';
($contactPhone = $config->contact->phone) != null || $contactPhone= 'Labshare Contact - (02) 9415 2975';
($contactEmail = $config->contact->email) != null || $contactEmail= 'Labshare Contact - labshare@uts.edu.au';
($contactAddress1 = $config->contact->address1) != null || $contactAddress1= 'Not Available';
($contactAddress2 = $config->contact->address2) != null || $contactAddress2= '';
?>

<?php if (count($this->messages)):?>
	<div class="ui-state-error ui-corner-all alertdiv">
	<?php if (count($this->messages) == 1):?>
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    		<?=$this->messages[0]?>
    	</p>
	<?php else: ?>
		<p class="alertp">
			<span class="ui-icon ui-icon-alert alertspan"></span>
			<strong>Alert:</strong>
		</p>
		<ul class="alertlist" >
    	<?php foreach ($this->messages as $m): ?>
    		<li><?=$m?></li>
    	<?php endforeach; ?>
    	</ul>
   	<?php endif; ?>
	</div>
<?php endif; ?>

<div align="center" style="width:100%">
     <?php echo $this->inst?>
</div>
<div id="contact name" align="center" style="width:100%" >
     <?php echo "Contact Name: ".$contactName?><br>
     <?php echo "Contact Phone: ".$contactPhone?><br>
     <?php echo "Contact Email: ".$contactEmail?><br>
     <?php echo "Contact Address: ".$contactAddress1?>
</div>

