<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 21st March 2010
 */
$this->headLink()->appendStylesheet($this->baseUrl('css/info.css'));
?>
<script>
  $(document).ready(function() {
    $("#accordion").accordion({ autoHeight: false });
  });
 </script>
<?php if (count($this->messages)):?>
	<div class="ui-state-error ui-corner-all alertdiv">
	<?php if (count($this->messages) == 1):?>
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    		<?=$this->messages[0]?>
    	</p>
	<?php else: ?>
		<p class="alertp">
			<span class="ui-icon ui-icon-alert alertspan"></span>
			<strong>Alert:</strong>
		</p>
		<ul class="alertlist" >
    	<?php foreach ($this->messages as $m): ?>
    		<li><?=$m?></li>
    	<?php endforeach; ?>
    	</ul>
   	<?php endif; ?>
	</div>
<?php endif; ?>

<div class="contentheader">
	<h2>News</h2>
</div>
<div class="bordered ui-corner-all"> 
	<div id="accordion" >
		<?php foreach ($this->news as $i => $news):?>
    		<h3><b><a href="#"><?php echo $news["header"]; ?></a></b></h3>
    		<div><?php echo $news["info"]; ?></div>
    	<?php endforeach;?>
    </div>
</div>


