<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Tania Machet (tmachet)
 * @date 9th April 2011
 *
 */
$this->headLink()->appendStylesheet($this->baseUrl('/css/session.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/reports.css'));
$this->headScript()->appendFile($this->baseUrl('/js/reports.js'));
$this->headScript()->appendFile($this->baseUrl('/js/jquery.dataTables.min.js'));
?>

<div class="contentheader">
	<h2>Access Report</h2>
</div>


<?php if($this->results)
{
	if(array_key_exists("accessReportData", $this->results)) 
	{
		
		foreach ($this->results->accessReportData as $row => $data)
		{
			foreach($data as $name => $value)
			{
       			switch($name)
        		{
        			case "user":
        				$tabledata[$row]["user"] = $value->userNamespace.':'.$value->userName;
        				break;
        			default:
        				$tabledata[$row][$name] = $value;
        		}
			}
		}
		?>
		<table id="accesstable">
		    <thead>
		        <tr>
		            <th>Date</th>
		            <th>User</th>
		            <th>User Class</th>
		            <th>Rig Type</th>
		            <th>Rig Name</th>
		            <th>Queue Duration</th>
		            <th>Session Start Time</th>
		            <th>Session End Time</th>
		            <th>Session Duration</th>
		            <th>Reason for Termination</th>
				</tr>
		    </thead>
		    <tbody>
		        <?php foreach ($tabledata as $rownum => $rowval):?>
		        <tr>
	            	<td><?=$rowval["sessionStartTime"]?></td>
	            	<td><?=$rowval["user"]?></td>
	            	<td><?=$rowval["userClass"]?></td>
	            	<td><?=$rowval["rigType"]?></td>
	            	<td><?=$rowval["rigName"]?></td>
	            	<td><?=$rowval["queueDuration"]?></td>
	            	<td><?=$rowval["sessionStartTime"]?></td>
	            	<td><?=$rowval["sessionEndTime"]?></td>
	            	<td><?=$rowval["sessionDuration"]?></td>
	            	<td><?=$rowval["reasonForTuermination"]?></td>
		        </tr>
               <?php endforeach ?>
		    </tbody>
		</table>
<?php }
	else
	{
		echo "There are no results for your search";
	}
}
else
{
	echo "No results param";
}
?>
<script>
	$(document).ready(function() {
		$('#accesstable').dataTable();
	} );
</script>


