<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Tania Machet (tmachet)
 * @date 9th April 2011
 *
 */
$this->headLink()->appendStylesheet($this->baseUrl('/css/session.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/reports.css'));
$this->headScript()->appendFile($this->baseUrl('/js/reports.js'));
$this->headScript()->appendFile($this->baseUrl('/js/jquery.dataTables.min.js'));
$this->headScript()->appendFile($this->baseUrl('/js/TableTools/media/js/TableTools.min.js'));
$this->headScript()->appendFile($this->baseUrl('/js/TableTools/media/js/ZeroClipboard.js'));

?>

<div class="reportingresults" >

<div class="contentheader">
	<h2>Access Report</h2>
</div>

<div class="description ui-toolbar ui-widget-header ui-corner-all ui-helper-clearfix" >
	  Searching for "<?=$this->search['accessvalue']?>" from  <?=$this->search['accessfrom']?> to
	   <?=$this->search['accessto']?> <br>
</div>

<?php if($this->results)
{
	if(array_key_exists("accessReportData", $this->results)) 
	{
	    ?>
		<table id="accesstable" cellpadding="0" cellspacing="0" border="0" >
		    <thead>
		        <tr>
		            <th>Date</th>
		            <th>User</th>
		            <th>User Class</th>
		            <th>Rig Type</th>
		            <th>Rig Name</th>
		            <th>In Queue (s)</th>
		            <th>Start</th>
		            <th>End</th>
		            <th>In Session (s)</th>
		            <th>Reason for Termination</th>
				</tr>
		    </thead>
		    <tbody>
	        <?php 
	        // Take into account single row
	        if(is_array($this->results->accessReportData))
	        { ?>
				<?php foreach ($this->results->accessReportData as $row => $data): 	?> 
			        <tr>
		            	<td><?=strtok($data->queueStartTime,'T')?></td>
		            	<td><?php echo $data->user->userNamespace.':'.$data->user->userName;?></td>
		            	<td><?=$data->userClass?></td>
		            	<td><?=$data->rigType?></td>
		            	<td><?=$data->rigName?></td>
		            	<td><?=$data->queueDuration?></td>
		            	<td><?php strtok($data->sessionStartTime,'T'); echo strtok('.');?></td>
		            	<td><?php strtok($data->sessionEndTime,'T'); echo strtok('.');?></td>
		            	<td><?=$data->sessionDuration?></td>
		            	<td><?=$data->reasonForTermination?></td>
			        </tr>
               <?php endforeach;
            }
            else
            {
              $data = $this->results->accessReportData ?>
		        <tr>
		            	<td><?=strtok($data->queueStartTime,'T')?></td>
		            	<td><?php echo $data->user->userNamespace.':'.$data->user->userName;?></td>
		            	<td><?=$data->userClass?></td>
		            	<td><?=$data->rigType?></td>
		            	<td><?=$data->rigName?></td>
		            	<td><?=$data->queueDuration?></td>
		            	<td><?php strtok($data->sessionStartTime,'T'); echo strtok('.');?></td>
		            	<td><?php strtok($data->sessionEndTime,'T'); echo strtok('.');?></td>
		            	<td><?=$data->sessionDuration?></td>
		            	<td><?=$data->reasonForTermination?></td>
			        </tr>
            <?php }?>
		    </tbody>
		</table>
	<div class="filler">
	</div>
    <?php }
	else
	{ ?>
		<div class="ui-state-error ui-corner-all noresults">
			<span class="ui-icon ui-icon-alert"></span>	
			There are no results for this search.
		</div>
	<table  class="hide"  id="accesstable" cellpadding="0" cellspacing="0" border="0" ></table>
	<?php }
}
else
{ ?>
		<div class="ui-state-error ui-corner-all noresults">
			<span class="ui-icon ui-icon-alert"></span>	
			The search was invald, please try again.
		</div>
	<table  class="hide"  id="accesstable" cellpadding="0" cellspacing="0" border="0" ></table>
	
<?php 	}
?>
</div>
<script>
$('#actionbar').hide();

$(document).ready(function() {
		var oTable = $('#accesstable').dataTable({
			"bJQueryUI": true,
			"sPaginationType": "full_numbers",
			"bStateSave": true,
			"aaSorting": [[ 0, "asc" ]],
			"sDom": 'Tlt<"filler"><"F"fip<"filler">>',
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	        "bAutoWidth": false,
			"aoColumns": [
				/* Date */  		{ "sWidth": "80px" },
				/* User */  		{ "sWidth": "100px" },
				/* User Class */  	{ "sWidth": "100px" },
				/* Rig Type */  	{ "sWidth": "100px" },
				/* Rig Name */  	{ "sWidth": "100px" },
				/* In Queue */  	{ "sWidth": "50px" },
				/* Start */  		{ "sWidth": "50px" },
				/* End */  			{ "sWidth": "50px" },
				/* In Session */	{ "sWidth": "50px" },
				/* Termination */	{ "sWidth": "200px" }
			 ],
			"oTableTools": {"aButtons": [ "csv", "pdf", "copy" ],
				"sSwfPath": "<?=$this->baseUrl('/js/TableTools/media/swf/copy_cvs_xls_pdf.swf')?>"
			}	 
		});

		/*if (!$.browser.msie)
		{
			$('td', oTable.fnGetNodes()).hover( function() {
			var iCol = $('td').index(this) % 10;
			var nTrs = oTable.fnGetNodes();
			$('td:nth-child('+(iCol+1)+')', nTrs).addClass( 'highlighted' );
			}, function() {
				$('td.highlighted', oTable.fnGetNodes()).removeClass('highlighted');
			});
		}*/

	});
</script>


