<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Tania Machet (tmachet)
 * @date 9th March 2011
 *
 */
$this->headLink()->appendStylesheet($this->baseUrl('/css/session.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/reports.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/jquery.ui.selectmenu.css'));
$this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.selectmenu.js'));
?>

<?php if (!$this->noPermissions): ?>

<div class="contentheader">
	<h2>Reports</h2>
</div>

<div class="reportscontainer ui-corner-all overlayelementhide">
	<div class="sessionpanelheader">
		<p><span class="ui-icon ui-icon-note sessionpanelheadericon"></span> Access Reports:</p>
	</div>
	<div class="reportdescription">
		<p>Access details per rig, rig type, class or user over a specified period.</p>
	</div>
	<div>
		<select class="reportdropdown ui-corner-all" name="accessgroup">
			<option value=rig>Rig Name</option>
			<option value=type>Rig Type</option>
			<option value=class>User Class</option>
			<option value=user>User</option>
		</select>
	</div>
</div>


<script type="text/javascript">
$('select').selectmenu({width:100});
</script>

<?php else : ?>
No permission to generate reports
<?php endif ?>


