<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Tania Machet (tmachet)
 * @date 9th March 2011
 *
 */
$this->headLink()->appendStylesheet($this->baseUrl('/css/session.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/reports.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/jquery.ui.selectmenu.css'));
$this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.selectmenu.js'));
$this->headScript()->appendFile($this->baseUrl('/js/reports.js'));
?>

<?php if (!$this->noPermissions): ?>

<div class="contentheader">
	<h2>Reports</h2>
</div>

<form>
<div class="reportscontainer ui-corner-all overlayelementhide">
	<div class="sessionpanelheader">
		<p><span class="ui-icon ui-icon-suitcase sessionpanelheadericon"></span> Access Reports:</p>
	</div>
	<div class="reportdescription">
		<p>This report supplies access details per rig, rig type, class or user over a specified period.
		The session details such as queue duration and session duration are reported per user for the selection. </p>
	</div>
	<div class="reportdropdown">
		<p>Select type:   
		<select class="group" name="accessgroup" >
			<option value=rig >Rig Name</option>
			<option value=type>Rig Type</option>
			<option value=class>User Class</option>
			<option value=user>User</option>
		</select></p>
	</div>
	<div class="valuedropdown">
		<p>Select value: <select  id="accessvalue" name="accessvalue">
		<?php foreach($this->rigNames as $field => $value): ?>
			<?php if ($field == "selectionResult"): ?>
				<option value=<?=$value?>> <?=$value?></option>
			<?php endif; ?>
		<?php endforeach; ?>
		<option value="test"> Test</option>
		</select></p>
	</div>
	<div id="accessdatepicker" class="ui-corner-all">
		<label for="accessfrom">Date from</label>
		<input type="text" id="accessfrom" name="accessfrom"/>
		<label for="accessto">to</label>
		<input type="text" id="accessto" name="accessto"/>
	</div>
	<div id="accesssubmit">
		<a id="accesssubmit" class="actiondialogbutton plaina ui-corner-all" href="#">
		<img src="<?=$this->baseUrl('images/1rightarrow.png')?>" alt="Submit" 
		  onclick="reportTest()"/><br />
	    Get Access Report</a>
	</div>
	<div style="clear: both" ></div>
</div>




<div class="reportscontainer ui-corner-all overlayelementhide">
	<div class="sessionpanelheader">
		<p><span class="ui-icon ui-icon-suitcase sessionpanelheadericon"></span> Usage Reports:</p>
	</div>
	<div class="reportdescription">
		<p>Usage statistics per rig, rig type, class or user over a specified period.
		This includes details on average, median, maximum and minimum usage for the selection.</p>
	</div>
	<div class="reportdropdown">
		<p>Select type: <select class="group" name="reportgroup" >
			<option value=rig >Rig Name</option>
			<option value=type>Rig Type</option>
			<option value=class>User Class</option>
			<option value=user>User</option>
		</select></p>
	</div>
	<div class="valuedropdown">
		<div class="ui-widget">
			<label for="tags">Select Value: </label>
			<input id="tags">
		</div>
	</div>
	<div id="reportdatepicker" class="ui-corner-all">
		<label for="reportfrom">Date from</label>
		<input type="text" id="reportfrom" name="reportfrom"/>
		<label for="reportto">to</label>
		<input type="text" id="reportto" name="reportto"/>
	</div>
	<div id="reportsubmit">
		<a id="reportsubmit" class="actiondialogbutton plaina ui-corner-all" href="#">
		<img src="<?=$this->baseUrl('images/1rightarrow.png')?>" alt="Submit" 
		  onclick="reportTest()"/><br />
	    Get Usage Report</a>
	</div>
	
	<div style="clear: both" ></div>
</div>
</form>


<script type="text/javascript">
$('select').selectmenu({width:200});
//$('.group').change(groupselect());

//TODO set max and min dates correctly
$(function() {
	var dates = $("#accessfrom, #accessto, #reportfrom, #reportto" ).datepicker({
		dateFormat: "dd-mm-yy",
		defaultDate: "+1d",
		changeMonth: true,
		numberOfMonths: 2,
		onSelect: function( selectedDate ) {
			var option = this.id == "from" ? "minDate" : "maxDate",
				instance = $( this ).data( "datepicker" ),
				date = $.datepicker.parseDate(
					instance.settings.dateFormat ||
					$.datepicker._defaults.dateFormat,
					selectedDate, instance.settings );
			dates.not( this ).datepicker( "option", option, date );
		}
	});
});


$(function() {
	var availableTags = [
		"ActionScript",
		"AppleScript",
		"Asp",
		"BASIC",
		"C",
		"C++",
		"Clojure",
		"COBOL",
		"ColdFusion",
		"Erlang",
		"Fortran",
		"Groovy",
		"Haskell",
		"Java",
		"JavaScript",
		"Lisp",
		"Perl",
		"PHP",
		"Python",
		"Ruby",
		"Scala",
		"Scheme"
	];
	$( "#tags" ).autocomplete({
		source: availableTags
	});
});


</script>


<?php else : ?>
No permission to generate reports
<?php endif ?>


