<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 4th April 2011
 */

$this->headLink()->appendStylesheet('/css/admin.css');

?>


<div class="contentheader">
	<h2>Create Permission Keys</h2>
</div>

<div id="permform" >
<form id="permissionform" method="POST">
    <table>
    	<tr>
    		<td>User Class:</td>
    		<td>
    			<select name="class">
    			<?php foreach ($this->classes as $c): ?>
    				<option value="<?=$c['id']?>"><?=$this->stringTransform($c['name'], '_', ' ')?></option>
    			<?php endforeach; ?>
    			</select>
    		</td>
    	</tr>
    	<tr>
    		<td>Number of Uses:</td>
    		<td>
    			<select name="uses">
    				<option value="1">1</option>
    				<option value="5">5</option>
    				<option value="10">10</option>
    				<option value="25">25</option>
    			</select>
			</td>
    	</tr>
    	<tr>
    		<td>Home Organisation:</td>
    		<td><input type="text" name="home" /></td>
    	</tr>
    	<tr>
    		<td>Affliation:</td>
    		<td><input type="text" name="aff" /></td>
    	</tr>
    	<tr>
    		<td>Number to generate:</td>
    		<td>
    			<select name="num">
    				<option value="1">1</option>
    				<option value="4">4</option>
    				<option value="8">8</option>
    				<option value="16">16</option>
				<option value="32">32</option>
    			</select>
    		</td>
    	</tr>
    </table>
    <div id="permsubmitbutton">
    	<input type="submit" value="Generate Keys" />
    </div>
</form>
</div>

<script type="text/javascript">
<!--
$(document).ready(function() {
	$("#permissionform").jqTransform();
});
//-->
</script>

<?php if ($this->keys): ?>
<div id="permkeylist">
<table>
	<tr>
		<th colspan="2">Permission Keys</th>
	</tr>
	<?php for ($i = 0; $i < count($this->keys); $i += 2): ?>
	<tr>
		<td><?=$this->keys[$i]?></td>
		<td><? if ($i + 1 < count($this->keys)) echo $this->keys[$i + 1]; ?></td>
	</tr>
	<?php endfor; ?>
</table>
</div>
<?php endif; ?>

