<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date <day> July 2010
 */

$this->headLink()->appendStylesheet($this->baseUrl('/css/admin.css'));
?>

<div class="contentheader">
	<h2><?=$this->stringTransform($this->rig->name, '_', ' ')?></h2>
</div>

<!-- Rig status -->
<div id="rigstatus">
	<?php if ($this->rig->isAlarmed): ?>
		<img src="<?=$this->baseUrl('/images/balls/red_anime.gif')?>" alt="Alarm" />
		<h3>Alarm: <?=$this->rig->offlineReason?></h3>
	<?php elseif (!$this->rig->isRegistered): ?>
		<img src="<?=$this->baseUrl('/images/balls/blue.gif')?>" alt="Alarm" />
		<h3>Not registered</h3>
	<?php elseif (!$this->rig->isOnline): ?>
		<img src="<?=$this->baseUrl('/images/balls/red.gif')?>" alt="Alarm" />
		<h3>Offline: <?=$this->rig->offlineUser?></h3>
	<?php elseif ($this->rig->isInSession): ?>
		<img src="<?=$this->baseUrl('/images/balls/yellow.gif')?>" alt="Alarm" />
		<h3>In use: <?=$this->rig->sessionUser?></h3>
	<?php else: ?>
		<img src="<?=$this->baseUrl('/images/balls/green.gif')?>" alt="Alarm" />
		<h3>Online</h3>
	<?php endif; ?>
</div>

<div id="rigpanels">

<!-- Offline times panel. -->
<div id="offlinepanel" class="panel ui-corner-all">
    <div class="paneltitle">
    	<span class="ui-icon ui-icon-wrench"></span>
    	Offline periods
    </div>
</div>

<!-- Rig logs. -->
<div id="logspanel" class="panel ui-corner-all">
	 <div class="paneltitle">
    	<span class="ui-icon ui-icon-script"></span>
    	Logs
    </div>
</div>

<div style="clear:both"> </div>
</div>

