<?php
/**
 * SAHARA Web Interface
 *
 * User interface to Sahara Remote Laboratory system.
 *
 * @license See LICENSE in the top level directory for complete license terms.
 *
 * Copyright (c) 2010, University of Technology, Sydney
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the University of Technology, Sydney nor the names
 *    of its contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Michael Diponio (mdiponio)
 * @date 21st July 2010
 */

$this->headLink()->appendStylesheet($this->baseUrl('css/home.css'));
$this->headScript()->appendFile($this->baseUrl('js/home.js'));
?>

<div class="contentheader">
    <h2>Data Files</h2>
</div>

<div id="homedirectory">

<div id="homedirmessage">

</div>

<?php if ($this->homeExists && count($this->files)): ?>
	<!-- Normal file listing. -->
<div id="homedircontainer" class="ui-corner-all">
	<div id="homedirheader">
		<span class="ui-icon ui-icon-folder-open" style="width:15px"></span>
		Select a file to download:
	</div>
	<div id="homedircontents">
		<ul id="homedirlist" style="width:550px">
		    <?php foreach($this->files as $name => $url): ?>
			<li>
				<a class="plaina hddownloadlink" href="/home/download<?=$url?>" style="width:450px">
					<span class="ui-icon ui-icon-circle-arrow-s" style="width:15px"></span><?=$name?>
				</a>
				<a class="plaina hddelfilelink" href="#" onclick="deleteHomeFile('<?=$name?>', '<?=$url?>');return false;">
					<span class="ui-icon ui-icon-trash"></span>Delete
				</a>
			</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<?php elseif (!count($this->files)): ?>
	<!-- No files. -->
	<div class="ui-state-error ui-corner-all alertdiv centercontent" style="width:360px">
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    		You currently have no files in your home directory.
    	</p>
    </div>

<?php else: ?>
	<!-- Error getting home directory. -->
	<div class="ui-state-error ui-corner-all alertdiv centercontent" style="width:360px">
		<p class="alertp">
    		<span class="ui-icon ui-icon-alert alertspan"></span>
    		Sorry, your home directory does not exist.<br />
    		&nbsp;&nbsp;Please use the 'Send Feedback' button to report this.
    	</p>
    </div>
<?php endif; ?>

</div>
